- hosts: all
  become: true
  tasks:
     - name: delete old deployment
       command: kubectl delete -f /root/deploy-webapp/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /root/deploy-webapp/Service.yml
     - name: create new deployment
       command: kubectl apply -f /root/deploy-webapp/Deployment.yml
     - name: create new service
       command: kubectl apply -f /root/deploy-webapp/Service.yml
